spring:
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring_jpa?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 123456
